version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3305:3306"
    volumes:
      - cardoso_data:/var/lib/mysql 
  
volumes:
  cardoso_data: