server:
    error:
        include-stacktrace: on-param

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: mysql
    jpa:
        hibernate:
          ddl-auto: update

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG

